# Generated by Django 2.2.4 on 2019-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_registration_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=100)),
                ('randomid', models.IntegerField(max_length=201)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
