# Generated by Django 2.2.4 on 2019-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_tempregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempregister',
            name='randomid',
            field=models.IntegerField(),
        ),
    ]
