# Generated by Django 2.2.4 on 2019-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190813_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempregister',
            name='randomid',
            field=models.IntegerField(max_length=50),
        ),
    ]
