# Generated by Django 2.2.4 on 2019-10-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cmspages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=150)),
                ('meta_keyword', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.CharField(max_length=300)),
                ('uniqueid', models.IntegerField(default=0, max_length=50, unique=True)),
            ],
        ),
    ]
