# Generated by Django 2.2.4 on 2020-01-29 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('logo_class', models.CharField(help_text='https://mdbootstrap.com/docs/jquery/content/icons-list/', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSmartPhoneAppTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_video', models.FileField(upload_to='about_video/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', models.TextField(max_length=5000)),
                ('about_image', models.ImageField(upload_to='about_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectivityDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSmartPhoneApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(upload_to='App_title_images/')),
                ('app_description', models.TextField(max_length=5000)),
                ('app_images', models.ImageField(upload_to='app_images/')),
                ('specification_title', models.CharField(max_length=200)),
                ('specification_logo_class', models.CharField(help_text='https://mdbootstrap.com/docs/jquery/content/icons-list/', max_length=200)),
                ('specification_description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.AboutSmartPhoneAppTitle')),
            ],
        ),
    ]
